### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by BitConf** [brutemap-dev/brutemap#3]
**Describe the bug**
Looks like not all requirements set in requirements.txt

**To Reproduce**
# git clone https://github.com/brutemap-dev/brutemap.git
# pip install -r requirements.txt
# python brutemap.py -h
Traceback (most recent call last):
  File "brutemap.py", line 24, in <module>
    from lib.controller.start import initialize
  File "/root/brutemap/lib/controller/start.py", line 8, in <module>
    from lib.controller.target import checkTarget
  File "/root/brutemap/lib/controller/target.py", line 8, in <module>
    import requests
ImportError: No module named requests

**Expected behavior**
The help screen output expected

**Desktop (please complete the following information):**
 - Linux bravo 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Python 2.7.12 (default, Nov 12 2018, 14:36:49)
 - [GCC 5.4.0 20160609] on linux2

**Comment by brutemap-dev** [comment]
thanks! but this is not a bug! dependency *requests* are already in the dependency list !. before running brutemap, make sure all dependencies are installed.
