### ISSUE TITLE
does this work on all type of auth sites like a html post one ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [brutemap-dev/brutemap#5]
i am talking about router pages like this 
![image](https://user-images.githubusercontent.com/20546638/61406246-c2bd4980-a8db-11e9-8bf8-50cd39d8ebc0.png)

**Comment by aprilahijriyan** [comment]
Hmmmm, sorry for the web router page, currently not supported. We will try to add this type of page, in the future.

**Comment by M-Julius** [comment]
it works for me, here I am trying to bruteforce mikrotik hotspot login with brutemap, review https://www.instagram.com/p/B0DbChZHLJS/?igshid=13vcyvcke3tdf

**Comment by minanagehsalalma** [comment]
@aprilahijriyan @M-Julius  
what about causes like this 
![image](https://user-images.githubusercontent.com/20546638/62716572-a73cee80-ba02-11e9-88c2-4151d57eec3a.png)
[source ](https://miloserdov.org/?p=1901)
does it still works  ? 
or in  cases like this 
https://www.reddit.com/r/AskNetsec/comments/c8c5pf/how_i_can_manually_login_to_hg_router_using_curl/

>  i looked in the page html and found that it does this
> 
> 1- Encrypt the password to sha256
> 
> 2- then base64 encode the sha256 hash
> 
> 3- then add the hash to the challange ( that it gets from another page )
> 
> 4- then sha 256 the outputthese code lines
> 
> var dbpass = base64encode(SHA256(Password.value));
>   var realpass = dbpass + challange;  
> form.addParameter('Password', SHA256(realpass));

@M-Julius  and about the mikrotik i think almost all of them use challenge and hex md5 
just like this 
```
	    function doLogin() {
		document.sendin.username.value = document.login.username.value;
		document.sendin.password.value = hexMD5('\350' + document.login.password.value + '\373\035\057\343\226\277\221\134\356\002\123\115\360\364\164\233');
		document.sendin.submit();
```

source `hexMD5('$(chap-id)' + passw + '$(chap-challenge)');`
`function hexMD5 (str) { return binl2hex(coreMD5( str2binl(str))) }
`http://portal.cloud-hotspot.com/md5.js



[page.zip](https://github.com/brutemap-dev/brutemap/files/3482603/page.zip)

**Comment by aprilahijriyan** [comment]
Hmm, I didn't test targets like the router page. I feel happy, if you want @minanagehsalalma to contribute.

**Comment by minanagehsalalma** [comment]
@aprilahijriyan in what ?

**Comment by aprilahijriyan** [comment]
@minanagehsalalma If you believe that the brutemap does not support the above target. Maybe you can help develop this project. thanks!

**Comment by minanagehsalalma** [comment]
@aprilahijriyan  sorry i don't know python and there is a lot more advanced tools out there just like the one in tutroial although it needs a bit automation  ....  i am not int
. Sorry again .
